"""add not null to fk

Revision ID: 030eeaa01088
Revises: 94e23f1523da
Create Date: 2023-07-11 16:16:23.225708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030eeaa01088'
down_revision = '94e23f1523da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.alter_column('scientist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('scientist_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
